In [5]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, *salaries):
        total_salary = sum(salaries) + self.salary
        num_employees = len(salaries) + 1
        return total_salary / num_employees


class FullTimeEmployee(Employee):
    def __init__(self, name, family, salary, department, hours_worked):
        super().__init__(name, family, salary, department)
        self.hours_worked = hours_worked

    def calculate_fulltime_salary(self):
        return self.salary * (self.hours_worked / 40)


# Create instances of Employee and FullTimeEmployee
emp1 = Employee("John", "Fam1", 500000, "MATH")
emp2 = Employee("Jane", "Fam2", 600000, "NNDL")

fulltime_employee = FullTimeEmployee("Smith", "Fam3", 700000, "IT", 35)

# Call member functions
average_salary = emp1.average_salary(emp2.salary)
fulltime_salary = fulltime_employee.calculate_fulltime_salary()

# Display results
print(f"Total number of employees: {Employee.employee_count}")
print(f"Average salary of employees: {average_salary}")
print(f"Full-time employee salary: {fulltime_salary}")


Total number of employees: 3
Average salary of employees: 550000.0
Full-time employee salary: 612500.0


In [3]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (along axis=1)
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

# Display the results
print("Random Vector:")
print(random_vector)
print("\nReshaped Array:")
print(reshaped_array)

Random Vector:
[ 8.64405707  4.22613875  0.          8.4910148   9.56667956 10.10267367
  3.54430526  0.          1.03684941 10.90237016  0.          9.28094656
 12.56597231 15.10748246 12.7099067  18.85331378  0.         18.03013597
  5.56007046  5.55230254]

Reshaped Array:
[[ 8.64405707  4.22613875  0.          8.4910148   9.56667956]
 [10.10267367  3.54430526  0.          1.03684941 10.90237016]
 [ 0.          9.28094656 12.56597231 15.10748246 12.7099067 ]
 [18.85331378  0.         18.03013597  5.56007046  5.55230254]]
